version: "3.7"
services:
  # mongodb
  mongodb:
    image: mongo:4.4.5
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - shared_network

  # mongo_express
  mongo_express:
    image: mongo-express:0.54
    depends_on:
      - mongodb
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - shared_network

  api:
    build:
      context: "Catalog API/"
      dockerfile: "Catalog API/Dockerfile"
    depends_on:
      - mongodb
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDbSettings:Host=mongodb
      - MongoDbSettings:Username=admin
      - MongoDbSettings:Password=password
      - JwtSettings:Key=This_Is_My_Secret_Jwt_Key
    networks:
      - shared_network

volumes:
  mongo_data:
networks:
  shared_network:
