version: "3.7"
services:
  # mongodb
  mongodb:
    image: mongo:4.4.5
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

  # mongo_express
  mongo_express:
    image: mongo-express:0.54
    depends_on:
      - mongodb
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - mongo_network

  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Catalog
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysqldb
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=3306
      - PMA_USER=admin
      - PMA_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - mysql_network

volumes:
  mongo_data:
  mysql_data:
networks:
  mongo_network:
  mysql_network:
